FROM python:3.8-slim-buster

# setting work directory
WORKDIR /usr/src/app

# env variables
ENV PYTHONBUFFERED 1
ENV PYTHONDONTWEITEBYTECODE 1

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# install psycopg dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# install dependencies
COPY ./requirements.dev.txt .
#RUN pip install  --no-cache-dir -r requirements.dev.txt

RUN pip install pip --upgrade && \
    pip install -r requirements.dev.txt
# copy entrypoint.sh
COPY ./entrypoint.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]


