version: '3.3'

services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    command: gunicorn --workers=5 -t 120   --log-level debug --access-logfile access.log --error-logfile error.log gifts_shaker.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./db.sqlite3:/home/app/web/db.sqlite3


