version: "2.2"


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /home/michal/database/:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app
    command: bash ./docker-entrypoint.sh
    ports:
      - 8080:8080
    depends_on:
      - db
